version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: stables-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'stables_management'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/stables_management_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: ./stable-management-rest
      dockerfile: Dockerfile
    container_name: stables-app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/stables_management?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db-data: